/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administrador;

import root.*;
import clases.Auto;
import clases.tiempo;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author vanes
 */
public class frm_horaFrac extends javax.swing.JFrame {

    public static LinkedList contenedorHora = new LinkedList();
    public int buscar;
    
    public frm_horaFrac() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarTiempo();
        txt_hora.setEditable(false);
        txt_fecha.setEditable(false);
    }
     tiempo tm=new tiempo();
    public void mostrarTiempo(){
         txt_hora.setText(tm.horaFormateada);
         txt_fecha.setText(tm.fechaFormateada);
    }
    
    public void mosLugar(){
        String panel=this.txt_lugar.getText();
        int lugar=Integer.parseInt(panel);
       if(lugar==1){
            this.pane_1.setBackground(Color.red);
       }
       if(lugar==2){
            this.pane_2.setBackground(Color.red);
       } 
       if(lugar==3){
            this.pane_3.setBackground(Color.red);
       } 
       if(lugar==4){
            this.pane_4.setBackground(Color.red);
       } 
       if(lugar==5){
            this.pane_5.setBackground(Color.red);
       } 
       if(lugar==6){
            this.pane_6.setBackground(Color.red);
       } 
       
    }   
    
    public void validar(){
        //Placa
         if(txt_placa.getText().isEmpty()){
            txt_placa.setBackground(new Color(251, 197, 197));
            lb_obligatorioP.setText("*Obligatorio");
           
        }else{
              txt_placa.setBackground(new Color(224, 251, 197));
              lb_obligatorioP.setText("");
        }
        
        //Lugar
         if(txt_lugar.getText().isEmpty()){
            txt_lugar.setBackground(new Color(251, 197, 197));
            lb_obligatorioL.setText("*Obligatorio");
           
        }else{
              txt_lugar.setBackground(new Color(224, 251, 197));
               lb_obligatorioL.setText("");
        }
        
        if(txt_placa.getText().isEmpty() ||
            txt_lugar.getText().isEmpty()  ){
           
             btn_guardar.setEnabled(false);
         }else{
             btn_guardar.setEnabled(true);
         }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pane_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pane_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pane_3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pane_4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pane_5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pane_6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txt_placa = new javax.swing.JTextField();
        txt_hora = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_lugar = new javax.swing.JTextField();
        lb_obligatorioP = new javax.swing.JLabel();
        lb_obligatorioL = new javax.swing.JLabel();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setText("Menu");
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 90, 30));

        jPanel2.setBackground(new java.awt.Color(126, 190, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pane_1.setBackground(new java.awt.Color(190, 247, 126));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");

        javax.swing.GroupLayout pane_1Layout = new javax.swing.GroupLayout(pane_1);
        pane_1.setLayout(pane_1Layout);
        pane_1Layout.setHorizontalGroup(
            pane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_1Layout.setVerticalGroup(
            pane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        pane_2.setBackground(new java.awt.Color(190, 247, 126));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");

        javax.swing.GroupLayout pane_2Layout = new javax.swing.GroupLayout(pane_2);
        pane_2.setLayout(pane_2Layout);
        pane_2Layout.setHorizontalGroup(
            pane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_2Layout.setVerticalGroup(
            pane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        pane_3.setBackground(new java.awt.Color(190, 247, 126));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");

        javax.swing.GroupLayout pane_3Layout = new javax.swing.GroupLayout(pane_3);
        pane_3.setLayout(pane_3Layout);
        pane_3Layout.setHorizontalGroup(
            pane_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_3Layout.setVerticalGroup(
            pane_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        pane_4.setBackground(new java.awt.Color(190, 247, 126));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");

        javax.swing.GroupLayout pane_4Layout = new javax.swing.GroupLayout(pane_4);
        pane_4.setLayout(pane_4Layout);
        pane_4Layout.setHorizontalGroup(
            pane_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_4Layout.setVerticalGroup(
            pane_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        pane_5.setBackground(new java.awt.Color(190, 247, 126));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");

        javax.swing.GroupLayout pane_5Layout = new javax.swing.GroupLayout(pane_5);
        pane_5.setLayout(pane_5Layout);
        pane_5Layout.setHorizontalGroup(
            pane_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_5Layout.setVerticalGroup(
            pane_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        pane_6.setBackground(new java.awt.Color(190, 247, 126));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");

        javax.swing.GroupLayout pane_6Layout = new javax.swing.GroupLayout(pane_6);
        pane_6.setLayout(pane_6Layout);
        pane_6Layout.setHorizontalGroup(
            pane_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_6Layout.setVerticalGroup(
            pane_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.add(pane_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 320, 360));

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconCostH.png"))); // NOI18N
        jLabel7.setText("Estacionamiento x hora\n");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 400, 100));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel8.setText("Placa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel9.setText("Hora");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel10.setText("Fecha");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel11.setText("Lugar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 160, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 420, 20));

        txt_placa.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_placaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_placaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, 30));

        txt_hora.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel1.add(txt_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 30));

        txt_fecha.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, 30));

        txt_lugar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_lugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lugarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lugarKeyTyped(evt);
            }
        });
        jPanel1.add(txt_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 80, 30));

        lb_obligatorioP.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lb_obligatorioP.setForeground(new java.awt.Color(153, 0, 51));
        lb_obligatorioP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lb_obligatorioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 110, 40));

        lb_obligatorioL.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lb_obligatorioL.setForeground(new java.awt.Color(153, 0, 51));
        lb_obligatorioL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lb_obligatorioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 120, 40));
        jPanel1.add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 830, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        String placa=txt_placa.getText();
        String hora=txt_hora.getText();
        String fecha=txt_fecha.getText();
        int lugar=Integer.parseInt(txt_lugar.getText());
        
        mosLugar();
        
        Auto horaFrac=new Auto(placa, hora, fecha, lugar);
        contenedorHora.add(horaFrac);
        
        txt_placa.setText("");
        txt_hora.setText(tm.horaFormateada);
        txt_fecha.setText(tm.fechaFormateada);
        txt_lugar.setText("");
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyTyped
        // TODO add your handling code here:
        
        //Limita la cantidad de carracteres (QWE-789-Q)
        if(txt_placa.getText().length()>=9){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
        //Busca los demas valores
          int press=evt.getKeyChar();
        if(press==10){
            String idEncontrado=txt_placa.getText().trim();
            Auto a;
            for(int i = 0; i < contenedorHora.size(); i++){
                a=(Auto)contenedorHora.get(i);
                if(idEncontrado.equalsIgnoreCase(a.getPlaca())){
            
                    txt_hora.setText(a.getHora());
                    txt_fecha.setText(a.getFecha());
                    txt_lugar.setText(Integer.toString(a.getLugar()));
                    
                    buscar=i;
                    break;
                    
                }//Fin if
                    
            }//fin for
            JOptionPane.showMessageDialog(null, "Placas de auto no encontradas");
        }//Fin if
    }//GEN-LAST:event_txt_placaKeyTyped

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        new panel_admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void txt_lugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lugarKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter((validar))){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txt_lugarKeyTyped

    private void txt_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_placaKeyReleased

    private void txt_lugarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lugarKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_lugarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_horaFrac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_horaFrac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_horaFrac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_horaFrac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_horaFrac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_obligatorioL;
    private javax.swing.JLabel lb_obligatorioP;
    private javax.swing.JPanel pane_1;
    private javax.swing.JPanel pane_2;
    private javax.swing.JPanel pane_3;
    private javax.swing.JPanel pane_4;
    private javax.swing.JPanel pane_5;
    private javax.swing.JPanel pane_6;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_lugar;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables
}
