/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administrador;

import com.login.*;
import root.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author vanes
 */
public class panel_admin extends javax.swing.JFrame {

    /**
     * Creates new form panel_root
     */
    public panel_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        tiempo();
    }
    
    public void tiempo(){
          Timer timer = new Timer(1000, e -> {
            Date date = new Date();

            SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormatter.format(date);
            lb_fecha.setText(formattedDate);

            SimpleDateFormat timeFormatter = new SimpleDateFormat("hh:mm:ss a");
            String formattedTime = timeFormatter.format(date);
            lb_hora.setText(formattedTime);

            
        });
        timer.start();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        btn_membresia = new javax.swing.JButton();
        btn_lugar = new javax.swing.JButton();
        btn_hora = new javax.swing.JButton();
        btn_salidaVehiculo = new javax.swing.JButton();
        btn_cerrarSesion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_renovacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 59, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/park1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 160));

        jLabel3.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 28));

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Hora");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, 30));

        lb_fecha.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lb_fecha.setForeground(new java.awt.Color(204, 204, 255));
        lb_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fecha.setText("dd/mm/yyyy");
        jPanel2.add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 110, 30));

        lb_hora.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lb_hora.setForeground(new java.awt.Color(204, 204, 255));
        lb_hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hora.setText("hh:mm:ss a.m");
        jPanel2.add(lb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 140, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Manual.png"))); // NOI18N
        jButton8.setText("Menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 280, 650));

        btn_membresia.setBackground(new java.awt.Color(153, 255, 153));
        btn_membresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/carroAgr.png"))); // NOI18N
        btn_membresia.setText("Membresia");
        btn_membresia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_membresia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_membresia.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_membresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_membresiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_membresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 80));

        btn_lugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Lugar.png"))); // NOI18N
        btn_lugar.setText("Lugar");
        btn_lugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_lugar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_lugar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lugarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 80));

        btn_hora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reloj.png"))); // NOI18N
        btn_hora.setText("Hora");
        btn_hora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hora.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_hora.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_horaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 80));

        btn_salidaVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/coche.png"))); // NOI18N
        btn_salidaVehiculo.setText("Salida vehiculos");
        btn_salidaVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salidaVehiculo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_salidaVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_salidaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salidaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 150, 80));

        btn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/salir.png"))); // NOI18N
        btn_cerrarSesion.setText("Cerar sesión");
        btn_cerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_cerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 150, 80));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 150, -1));

        btn_renovacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/renovacion.png"))); // NOI18N
        btn_renovacion.setText("Renovacion");
        btn_renovacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_renovacion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_renovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_renovacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_renovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 150, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/FondoMenu.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_membresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_membresiaActionPerformed
        // TODO add your handling code here:
        new frm_membresia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_membresiaActionPerformed

    private void btn_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_horaActionPerformed
        // TODO add your handling code here:
        new frm_horaFrac().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_horaActionPerformed

    private void btn_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lugarActionPerformed
        // TODO add your handling code here:
        new csl_lugar().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_lugarActionPerformed

    private void btn_salidaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaVehiculoActionPerformed
        // TODO add your handling code here:
        new salida_vehiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_salidaVehiculoActionPerformed

    private void btn_renovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_renovacionActionPerformed
        // TODO add your handling code here:
        new frm_renovacion().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_renovacionActionPerformed

    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
        // TODO add your handling code here:
        new login_admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            String url="C:\\Users\\vanes\\OneDrive\\Escritorio\\POO\\Manual_ParkCar.pdf";
            ProcessBuilder p=new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarSesion;
    private javax.swing.JButton btn_hora;
    private javax.swing.JButton btn_lugar;
    private javax.swing.JButton btn_membresia;
    private javax.swing.JButton btn_renovacion;
    private javax.swing.JButton btn_salidaVehiculo;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    // End of variables declaration//GEN-END:variables
}
